"""added emergency mail

Revision ID: 0aea438d9233
Revises: 509305e864ac
Create Date: 2021-11-05 10:49:30.289952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aea438d9233'
down_revision = '509305e864ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('emergencyEmail', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'emergencyEmail')
    # ### end Alembic commands ###
