"""migrate

Revision ID: 4d30b64cb38e
Revises: 8ad97ecc3595
Create Date: 2021-11-05 09:39:29.833279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d30b64cb38e'
down_revision = '8ad97ecc3595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('address', sa.String(length=50), nullable=True))
    op.add_column('patient', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('patient', sa.Column('region', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'region')
    op.drop_column('patient', 'city')
    op.drop_column('patient', 'address')
    # ### end Alembic commands ###
