"""migrates

Revision ID: 509305e864ac
Revises: 4d30b64cb38e
Create Date: 2021-11-05 10:37:24.633202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509305e864ac'
down_revision = '4d30b64cb38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('email', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'email')
    # ### end Alembic commands ###
